name: Build GUI exe with Pyinstaller

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'test build tags'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10' 

    -run: pip3 install pyinstaller pysimplegui
    -run: pyinstaller --onefile --noconsole --distpath=dist/linux src/app.py


    - uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: dist/linux

    
  